### ISSUE TITLE
long-press is not working in CoreELEC 8.90.2

### ISSUE THREAD

**Issue by sinancetinkaya** [CoreELEC/CoreELEC#75]
"IR switched to keyboard mode (long-press now supported)" feature introduced in CoreELEC 8.90.1 is not working in CoreELEC 8.90.2

**Comment by boot2k3** [comment]
It works
copy empty “98-eventlircd.rules” to “/storage/.config/udev.rules.d/”
https://discourse.coreelec.org/t/howto-configure-ir-remote-control/31/8

**Comment by Raybuntu** [comment]
eventlircd was add back to solve remote issues for some people.

systemctl mask eventlircd 
Will fix it for good for you.

**Comment by sinancetinkaya** [comment]
@Raybuntu When I use "systemctl mask eventlircd", some keys are not working.
I have Mecool KII Pro.

**Comment by adamg88** [comment]
@sinancetinkaya following the comments by @boot2k3 will have the same effect as the instructions given by @Raybuntu it wasn't needed because we changed how IR was initialized but it caused more problems than we anticipated so as soon as the core issue was fixed in Kodi we changed things back.

You can create a configuration for your remote to add long press options but this is not the place for it, the issue system is for reporting bugs and not for support, that is what the forums are there for.

It may help as well if you described what keys exactly are not working as well as your comment is rather vague to say the least.

**Comment by sinancetinkaya** [comment]
Oh man thanks for clearing this up. I'd have never figured out what the issue system was for...
As anyone can easily understand from the first post that I created this as a bug report because the changelog has no mention that eventlircd was reverted back.

**Comment by adamg88** [comment]
It does say `IR issues resolved` in the changelog but I guess this was rather vague on my part, there was a lot of discussion on the forums before 8.90.2 was released stating that things would be reverted so maybe you missed those posts.

If you want to continue using your remote in keyboard mode the keys are labeled differently and there is additional steps for remapping buttons that don't work, boot2k3 has posted a good example of the X92 config in the forums with long press support so you can look at that for ideas on how to create a config customized to your remote.
